### ISSUE TITLE
Only first page of multi-page lists is retrieved

### ISSUE THREAD

**Issue by EnigmaTriton** [woctezuma/SensCritique-Takeout#35]
When viewing a list of more than 30 elements, it's split into pages of 30 elements maximum.
SensCritique-Takeout does not handle this part and only the first page is retrieved.

Example: https://www.senscritique.com/liste/Collection_Vinyles/185800 shows 173 albums split into 6 pages (5×30 + 23).
But this module only takes the first page as shown below.

```python
>>> data = senscritique.parse_and_cache(user_name='Kwack', data_type='listes')
…
>>> len(data.get(185800).get('elements'))
30
```

**Comment by woctezuma** [comment]
Thank you. This should be fixed by v.0.5.1.

![proof](https://i.imgur.com/bFisALN.png)

**Comment by EnigmaTriton** [comment]
Correction confirmed on other lists (much longer to download but complete).
Great reactivity, thanks.
