### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by lk-minot** [woctezuma/SensCritique-Takeout#54]
I think the big update of the website broke the script

```
data = senscritique.parse_and_cache(user_name='wok', data_type='critiques')
Parsing 1 pages of critiques by wok.
https://www.senscritique.com/wok/critiques/page-1
[critiques ; page n°1] num_items = 0
[critiques by wok] num_items = 0
```

**Comment by woctezuma** [comment]
Yes, that is what I feared when it happened. Thank you for reporting the issue! I will see what I can do about that.

**Comment by lk-minot** [comment]
Thanks for the quick answer, I managed to do what i wanted with [senscritiquescraper](https://github.com/dbeley/senscritiquescraper) that seem to use old.senscritique.com as entry point

**Comment by woctezuma** [comment]
Thank you! I did not know about this tool!
